# Generated by Django 6.1.1 on 2026-09-16 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0006_plan_auto_renew_enabled'),
        ('organizations', '0003_protect_provider_contract_identity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250, verbose_name='nombre completo')),
                ('auto_renew_allowed', models.BooleanField(default=True, verbose_name='permite renovación automática')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='organizations.business', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'Afiliado',
                'verbose_name_plural': 'Afiliados',
                'ordering': ('full_name', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='PlanEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending_payment', 'Pendiente de pago'), ('active', 'Activa'), ('suspended', 'Suspendida'), ('expired', 'Vencida'), ('cancelled', 'Cancelada')], default='pending_payment', max_length=20, verbose_name='estado')),
                ('start_date', models.DateField(verbose_name='inicio')),
                ('end_date', models.DateField(verbose_name='fin exclusivo')),
                ('duration_months', models.PositiveIntegerField(verbose_name='duración en meses calendario')),
                ('provider_contact_name', models.CharField(blank=True, max_length=200, verbose_name='contacto del Proveedor')),
                ('provider_contact_email', models.EmailField(blank=True, max_length=254, verbose_name='correo del Proveedor')),
                ('provider_contact_phone', models.CharField(blank=True, max_length=50, verbose_name='teléfono del Proveedor')),
                ('provider_service_instructions', models.TextField(blank=True, verbose_name='instrucciones del Proveedor')),
                ('override_reason', models.TextField(blank=True, verbose_name='motivo de excepción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada el')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_enrollments', to='organizations.business', verbose_name='empresa')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_plan_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='creada por')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='enrollments.member', verbose_name='Afiliado')),
                ('plan_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='catalog.planversion', verbose_name='versión de Plan')),
                ('preceding_enrollment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='renewal', to='enrollments.planenrollment', verbose_name='Póliza anterior')),
            ],
            options={
                'verbose_name': 'Póliza',
                'verbose_name_plural': 'Pólizas',
                'ordering': ('-start_date', '-pk'),
                'constraints': [models.CheckConstraint(condition=models.Q(('duration_months__gt', 0)), name='ck_enrollment_positive_duration'), models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='ck_enrollment_effective_dates'), models.CheckConstraint(condition=models.Q(('pk', models.F('preceding_enrollment')), _negated=True), name='ck_enrollment_not_self_preceding')],
            },
        ),
    ]
