# Generated by Django 6.1.1 on 2026-09-17 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_protect_enrollment_terms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250, verbose_name='nombre completo')),
                ('relationship', models.CharField(max_length=100, verbose_name='parentesco o relación')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='fecha de nacimiento')),
                ('country_code', models.CharField(default='MX', max_length=2, verbose_name='país')),
                ('gender', models.CharField(choices=[('female', 'Mujer'), ('male', 'Hombre'), ('non_binary', 'No binario'), ('unspecified', 'No especificado')], default='unspecified', max_length=20, verbose_name='género')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='correo electrónico')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='teléfono')),
                ('attribution_source', models.CharField(blank=True, max_length=200, verbose_name='fuente de atribución')),
                ('do_not_contact', models.BooleanField(default=False, verbose_name='no contactar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beneficiaries', to='enrollments.planenrollment', verbose_name='Póliza')),
            ],
            options={
                'verbose_name': 'Beneficiario',
                'verbose_name_plural': 'Beneficiarios',
                'ordering': ('full_name', 'pk'),
            },
        ),
    ]
