# Generated by Django 6.1.1 on 2026-09-17 01:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0003_beneficiary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='member', to=settings.AUTH_USER_MODEL, verbose_name='cuenta'),
        ),
        migrations.AddField(
            model_name='member',
            name='attribution_source',
            field=models.CharField(blank=True, max_length=200, verbose_name='fuente de atribución'),
        ),
        migrations.AddField(
            model_name='member',
            name='country_code',
            field=models.CharField(default='MX', max_length=2, verbose_name='país'),
        ),
        migrations.AddField(
            model_name='member',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='eliminado el'),
        ),
        migrations.AddField(
            model_name='member',
            name='do_not_contact',
            field=models.BooleanField(default=False, verbose_name='no contactar'),
        ),
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='correo electrónico'),
        ),
        migrations.AddField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('female', 'Mujer'), ('male', 'Hombre'), ('non_binary', 'No binario'), ('unspecified', 'No especificado')], default='unspecified', max_length=20, verbose_name='género'),
        ),
        migrations.AddField(
            model_name='member',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='teléfono'),
        ),
    ]
