# Generated by Django 6.1.1 on 2026-09-17 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0004_member_account_member_attribution_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, verbose_name='correo electrónico'),
        ),
        migrations.RunSQL(
            sql="""
                CREATE FUNCTION enrollments_protect_beneficiary_term() RETURNS trigger
                LANGUAGE plpgsql AS $$
                BEGIN
                    IF TG_OP = 'DELETE' THEN
                        RAISE EXCEPTION 'beneficiaries cannot be deleted'
                            USING ERRCODE = '23514';
                    END IF;
                    IF NEW.enrollment_id IS DISTINCT FROM OLD.enrollment_id THEN
                        RAISE EXCEPTION 'beneficiary enrollment is immutable'
                            USING ERRCODE = '23514';
                    END IF;
                    RETURN NEW;
                END;
                $$;

                CREATE TRIGGER enrollments_beneficiary_term_immutable
                BEFORE UPDATE OR DELETE ON enrollments_beneficiary
                FOR EACH ROW EXECUTE FUNCTION enrollments_protect_beneficiary_term();
            """,
            reverse_sql="""
                DROP TRIGGER enrollments_beneficiary_term_immutable
                    ON enrollments_beneficiary;
                DROP FUNCTION enrollments_protect_beneficiary_term();
            """,
        ),
    ]
