# Generated by Django 6.1.1 on 2026-09-15 07:52

import django.db.models.deletion
import organizations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistanceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='eliminado el')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='nombre')),
                ('contact_name', models.CharField(blank=True, max_length=200, verbose_name='nombre de contacto')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='correo de contacto')),
                ('contact_phone', models.CharField(blank=True, max_length=50, verbose_name='teléfono de contacto')),
                ('service_instructions', models.TextField(blank=True, verbose_name='instrucciones de servicio')),
            ],
            options={
                'verbose_name': 'proveedor de asistencia',
                'verbose_name_plural': 'proveedores de asistencia',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='eliminado el')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('timezone', models.CharField(default='America/Mexico_City', max_length=100, validators=[organizations.models.validate_iana_timezone], verbose_name='zona horaria')),
            ],
            options={
                'verbose_name': 'empresa',
                'verbose_name_plural': 'empresas',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Reseller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='eliminado el')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'revendedor',
                'verbose_name_plural': 'revendedores',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ProviderAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='eliminado el')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('contact_name_override', models.CharField(blank=True, max_length=200, verbose_name='nombre de contacto específico')),
                ('contact_email_override', models.EmailField(blank=True, max_length=254, verbose_name='correo de contacto específico')),
                ('contact_phone_override', models.CharField(blank=True, max_length=50, verbose_name='teléfono de contacto específico')),
                ('service_instructions_override', models.TextField(blank=True, verbose_name='instrucciones de servicio específicas')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provider_assignments', to='organizations.business', verbose_name='empresa')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='business_assignments', to='organizations.assistanceprovider', verbose_name='proveedor')),
            ],
            options={
                'verbose_name': 'asignación de proveedor',
                'verbose_name_plural': 'asignaciones de proveedores',
                'ordering': ('business__name', 'provider__name'),
            },
        ),
        migrations.AddField(
            model_name='business',
            name='reseller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='businesses', to='organizations.reseller', verbose_name='revendedor'),
        ),
        migrations.CreateModel(
            name='ScopedAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('reseller_admin', 'Administrador de revendedor'), ('provider_employee', 'Empleado de proveedor'), ('tenant_admin', 'Administrador de empresa')], max_length=30, verbose_name='rol')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='revocado el')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_assignments', to='organizations.business', verbose_name='empresa')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='granted_scoped_assignments', to=settings.AUTH_USER_MODEL, verbose_name='otorgado por')),
                ('provider_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_assignments', to='organizations.providerassignment', verbose_name='contexto de proveedor y empresa')),
                ('reseller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_assignments', to='organizations.reseller', verbose_name='revendedor')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revoked_scoped_assignments', to=settings.AUTH_USER_MODEL, verbose_name='revocado por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scoped_assignments', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'asignación de alcance',
                'verbose_name_plural': 'asignaciones de alcance',
                'ordering': ('user__email', 'role'),
            },
        ),
        migrations.AddConstraint(
            model_name='providerassignment',
            constraint=models.UniqueConstraint(fields=('business', 'provider'), name='uq_provider_assignment_business_provider'),
        ),
        migrations.AddConstraint(
            model_name='business',
            constraint=models.UniqueConstraint(fields=('reseller', 'name'), name='uq_business_reseller_name'),
        ),
        migrations.AddConstraint(
            model_name='scopedassignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('business__isnull', True), ('provider_assignment__isnull', True), ('reseller__isnull', False), ('role', 'reseller_admin')), models.Q(('business__isnull', True), ('provider_assignment__isnull', False), ('reseller__isnull', True), ('role', 'provider_employee')), models.Q(('business__isnull', False), ('provider_assignment__isnull', True), ('reseller__isnull', True), ('role', 'tenant_admin')), _connector='OR'), name='ck_scoped_assignment_matching_scope'),
        ),
        migrations.AddConstraint(
            model_name='scopedassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('reseller__isnull', False), ('revoked_at__isnull', True)), fields=('user', 'reseller'), name='uq_scoped_assignment_user_reseller'),
        ),
        migrations.AddConstraint(
            model_name='scopedassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_assignment__isnull', False), ('revoked_at__isnull', True)), fields=('user', 'provider_assignment'), name='uq_scoped_assignment_user_provider'),
        ),
        migrations.AddConstraint(
            model_name='scopedassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('business__isnull', False), ('revoked_at__isnull', True)), fields=('user', 'business'), name='uq_scoped_assignment_user_business'),
        ),
    ]
