# Generated by Django 6.1.1 on 2026-09-16 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scopedassignment',
            options={'ordering': ('user__email', 'role'), 'verbose_name': 'asignación de permisos', 'verbose_name_plural': 'asignaciones de permisos'},
        ),
    ]
