# Generated by Django 6.1.1 on 2026-09-15 06:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_email_verified_at_accountproof'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernmentIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('mx_rfc', 'RFC de México')], max_length=20)),
                ('lookup_digest', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='government_identifiers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('kind', 'lookup_digest'), name='uq_government_identifier_kind_lookup')],
            },
        ),
    ]
