# Generated by Django 6.1.1 on 2026-09-15 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_governmentidentifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountproof',
            name='purpose',
            field=models.CharField(choices=[('activation', 'Activación'), ('password_reset', 'Restablecimiento de contraseña')], max_length=20),
        ),
    ]
