# Generated by Django 6.1.1 on 2026-09-15 06:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_accountproof_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountproof',
            name='requested_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='accountproof',
            name='purpose',
            field=models.CharField(choices=[('activation', 'Activación'), ('password_reset', 'Restablecimiento de contraseña'), ('email_change', 'Cambio de correo')], max_length=20),
        ),
        migrations.CreateModel(
            name='AccountSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
