# Generated by Django 6.1.1 on 2026-09-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditevent',
            name='active_scope_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='active_scope_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
