# Generated by Django 6.1.1 on 2026-09-16 06:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_permission_labels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('internal_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='importe interno')),
                ('currency', models.CharField(default='MXN', max_length=3, validators=[django.core.validators.RegexValidator('^[A-Z]{3}$', 'Usa un código de moneda de tres letras.')], verbose_name='moneda interna')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('provider', models.ForeignKey(help_text='El Proveedor es permanente. Para cambiarlo debes crear un nuevo Plan; las versiones anteriores conservan su Proveedor.', on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='organizations.assistanceprovider', verbose_name='Proveedor permanente')),
                ('reseller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='organizations.reseller', verbose_name='revendedor')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
                'ordering': ('name', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='PlanVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='versión')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicada')], default='draft', max_length=20, verbose_name='estado')),
                ('effective_from', models.DateField(verbose_name='vigente desde')),
                ('effective_until', models.DateField(verbose_name='vigente hasta (fecha exclusiva)')),
                ('duration_months', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='duración en meses calendario')),
                ('coverage_terms', models.TextField(verbose_name='condiciones de cobertura')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='publicada el')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada el')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_plan_versions', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='catalog.plan', verbose_name='Plan')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='published_plan_versions', to=settings.AUTH_USER_MODEL, verbose_name='publicada por')),
            ],
            options={
                'verbose_name': 'versión de Plan',
                'verbose_name_plural': 'versiones de Plan',
                'ordering': ('-number',),
            },
        ),
        migrations.CreateModel(
            name='PlanService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='servicio para el Afiliado')),
                ('coverage_terms', models.TextField(verbose_name='condiciones del servicio')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='catalog.planversion', verbose_name='versión')),
            ],
            options={
                'verbose_name': 'servicio de Plan',
                'verbose_name_plural': 'servicios de Plan',
                'ordering': ('pk',),
            },
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.CheckConstraint(condition=models.Q(('internal_amount__isnull', True), ('internal_amount__gte', 0), _connector='OR'), name='ck_plan_nonnegative_amount'),
        ),
        migrations.AddConstraint(
            model_name='planversion',
            constraint=models.UniqueConstraint(fields=('plan', 'number'), name='uq_plan_version_number'),
        ),
        migrations.AddConstraint(
            model_name='planversion',
            constraint=models.CheckConstraint(condition=models.Q(('duration_months__gt', 0), ('number__gt', 0)), name='ck_plan_version_positive_months_number'),
        ),
        migrations.AddConstraint(
            model_name='planversion',
            constraint=models.CheckConstraint(condition=models.Q(('effective_until__gt', models.F('effective_from'))), name='ck_plan_version_effective_dates'),
        ),
        migrations.AddConstraint(
            model_name='planversion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('published_at__isnull', True), ('published_by__isnull', True), ('status', 'draft')), models.Q(('published_at__isnull', False), ('published_by__isnull', False), ('status', 'published'), models.Q(('author', models.F('published_by')), _negated=True)), _connector='OR'), name='ck_plan_version_two_person_publication'),
        ),
    ]
