# Generated by Django 6.1.1 on 2026-09-16 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_protect_published_terms'),
        ('organizations', '0002_permission_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='availability',
            field=models.CharField(choices=[('all_businesses', 'Todas las empresas'), ('selected_businesses', 'Empresas seleccionadas')], default='all_businesses', max_length=30, verbose_name='disponibilidad'),
        ),
        migrations.CreateModel(
            name='PlanBusinessAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_availabilities', to='organizations.business', verbose_name='empresa')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_availabilities', to='catalog.plan', verbose_name='Plan')),
            ],
            options={
                'verbose_name': 'disponibilidad de Plan',
                'verbose_name_plural': 'disponibilidades de Plan',
                'ordering': ('business__name', 'pk'),
            },
        ),
        migrations.AddField(
            model_name='plan',
            name='selected_businesses',
            field=models.ManyToManyField(related_name='selected_plans', through='catalog.PlanBusinessAvailability', to='organizations.business', verbose_name='empresas seleccionadas'),
        ),
        migrations.AddConstraint(
            model_name='planbusinessavailability',
            constraint=models.UniqueConstraint(fields=('plan', 'business'), name='uq_plan_business_availability'),
        ),
    ]
