# Generated by Django 6.1.1 on 2026-09-16 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_plan_service_coverage_contents'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='auto_renew_enabled',
            field=models.BooleanField(default=False, verbose_name='renovación automática habilitada'),
        ),
    ]
